services:
  note-bot:
    build: .
    container_name: note-bot
    restart: always
    command: [ "uv", "run", "python", "src/main.py" ]
    volumes:
      - /tmp/bot_pipe:/tmp/bot_pipe
      - ../logs:/logs
    ports:
      - "8002:8000"
    networks:
      - pomodoro-net


networks:
  pomodoro-net:
    external: true