"""initial

Revision ID: b5dfc3b07114
Revises: 
Create Date: 2025-07-10 17:35:25.703109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5dfc3b07114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'user_id',
                type_=sa.Integer(),
                postgresql_using="user_id::integer",
                existing_nullable=True)
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
